# Generated by Django 5.0 on 2024-02-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='adress_line_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='adress_line_2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
