# Generated by Django 5.0 on 2024-01-30 07:51

import technician.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0002_alter_technician_service_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=technician.models.TechnicianImagePath('profile_pictures')),
        ),
    ]
