# Generated by Django 5.0 on 2024-02-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0004_remove_technician_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='is_available_status',
            field=models.BooleanField(default=False),
        ),
    ]
